name: Auto Fix Dependabot Dependency Alert
on: pull_request
permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to private container registry for dependencies
        uses: docker/login-action@v1
        with:
          registry: https://1234567890.dkr.ecr.us-east-1.amazonaws.com
          username: ${{secrets.READONLY_AWS_ACCESS_KEY_ID}}
          password: ${{secrets.READONLY_AWS_ACCESS_KEY}}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
